import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen">
      <Header />
      <main className="py-24 bg-white">
        <div className="max-w-4xl mx-auto px-6 md:px-8">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-8 transition-colors"
            data-testid="link-back-home"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>

          <article className="prose prose-lg max-w-none">
            <h1>Privacy Policy</h1>
            <p className="text-muted-foreground">Last updated: October 6, 2025</p>

            <p>
              This Privacy Policy describes how FirePath ("we", "us", or "our") collects, uses, and protects your information when you use the FirePath mobile application (the "Service"). FirePath is developed by an independent developer and is designed with privacy-first principles.
            </p>

            <p>By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.</p>

            <h2>Interpretation and Definitions</h2>

            <h3>Definitions</h3>

            <p>For the purposes of this Privacy Policy:</p>

            <ul>
              <li><strong>Account</strong> means a unique account created for you to access our Service or parts of our Service through authentication providers.</li>
              <li><strong>Application</strong> refers to FirePath, the mobile application provided by the independent developer.</li>
              <li><strong>Developer</strong> (referred to as either "the Developer", "We", "Us" or "Our" in this Agreement) refers to the independent developer of FirePath.</li>
              <li><strong>Device</strong> means any mobile device that can access the Service such as a smartphone or tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the FirePath mobile application.</li>
              <li><strong>Third-Party Service Provider</strong> means any natural or legal person who processes the data on behalf of the Developer. This includes Google (for authentication), Apple (for authentication), and Firebase (for cloud storage services).</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, app usage patterns and calculation history).</li>
              <li><strong>You</strong> means the individual accessing or using the Service.</li>
            </ul>

            <h2>Collecting and Using Your Personal Data</h2>

            <h3>Types of Data Collected</h3>

            <h4>Personal Data</h4>

            <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</p>

            <p><strong>Authentication Data (when you sign in):</strong></p>
            <ul>
              <li>Email address (from Google Sign-In or Apple Sign-In)</li>
              <li>First name and last name (from authentication providers)</li>
              <li>Profile picture (from authentication providers)</li>
            </ul>

            <p><strong>Financial Data (Required for App Functionality):</strong></p>
            <ul>
              <li>FIRE calculation inputs and results</li>
              <li>Saved scenarios</li>
            </ul>

            <p><strong>App Usage Data:</strong></p>
            <ul>
              <li>User preferences (currency selection, theme settings)</li>
              <li>Calculation history and saved scenarios</li>
              <li>App usage patterns for functionality improvement</li>
            </ul>

            <p><strong>Technical Data:</strong></p>
            <ul>
              <li>Device ID (generated locally for sync conflict resolution)</li>
              <li>Authentication tokens (stored securely on device)</li>
            </ul>

            <h4>Usage Data</h4>

            <p>Usage Data is collected automatically when using the Service and includes:</p>
            <ul>
              <li>App usage patterns and feature interactions</li>
              <li>Calculation history and saved scenarios</li>
              <li>Error logs for app improvement (no personal data included)</li>
              <li>Performance metrics for app optimization</li>
            </ul>

            <p><strong>Important:</strong> We do not collect IP addresses, browser information, or device identifiers for tracking purposes. The app is designed to work primarily offline; when you sign in, cloud synchronization is enabled to provide cross-device access.</p>

            <h3>Use of Your Personal Data</h3>

            <p>The Developer may use Personal Data for the following purposes:</p>

            <ul>
              <li><strong>To provide and maintain our Service</strong>, including FIRE calculations, financial projections, and investment tracking.</li>
              <li><strong>To manage Your Account</strong>: to manage your registration as a user of the Service through authentication providers.</li>
              <li><strong>To provide core functionality</strong>: to perform FIRE calculations, generate financial projections, and track investment progress.</li>
              <li><strong>To provide cloud synchronization when you sign in</strong>: cloud sync is enabled by default upon sign-in to sync your data across devices.</li>
              <li><strong>To improve the Service</strong>: to analyze usage patterns and improve app functionality (without collecting personal financial data).</li>
              <li><strong>To provide user support</strong>: to respond to your inquiries and provide technical support.</li>
            </ul>

            <h3>Data Storage and Security</h3>

            <p><strong>Local-First Architecture:</strong></p>
            <ul>
              <li>When you are not signed in, all your data is stored locally on your device by default</li>
              <li>Data is encrypted using device security features (Keychain on iOS, Encrypted SharedPreferences on Android)</li>
              <li>When you sign in, your data is synchronized with Firebase cloud by default to enable cross-device access</li>
            </ul>

            <p><strong>Cloud Synchronization (when signed in):</strong></p>
            <ul>
              <li>Cloud sync is enabled by default upon sign-in</li>
              <li>Data is encrypted and stored securely using Firebase/Firestore</li>
              <li>You can sign out to stop future syncing; you may also delete cloud data via app settings</li>
              <li>Cloud sync allows you to access your data across multiple devices</li>
            </ul>

            <p><strong>Data Encryption:</strong></p>
            <ul>
              <li>All sensitive data is encrypted both locally and in cloud storage</li>
              <li>Authentication tokens are stored securely using platform-specific secure storage</li>
              <li>Financial calculations and personal data are protected with industry-standard encryption</li>
            </ul>

            <h3>Data Sharing</h3>

            <p>We may share your personal information in the following limited situations:</p>

            <ul>
              <li><strong>With Authentication Providers</strong>: We share minimal data (email, name, profile picture) with Google and Apple for authentication purposes only.</li>
              <li><strong>With Firebase</strong>: When you sign in, your encrypted data is stored on Firebase servers for cross-device synchronization.</li>
              <li><strong>No Data Selling</strong>: We do not sell, rent, or trade your personal information to third parties.</li>
              <li><strong>No Analytics or Tracking</strong>: We do not use analytics services or track your behavior across other apps or websites.</li>
            </ul>

            <h3>Retention of Your Personal Data</h3>

            <p><strong>Local Data:</strong></p>
            <ul>
              <li>Data stored locally on your device remains until you delete the app or manually delete specific data</li>
              <li>You have full control over your local data at all times</li>
            </ul>

            <p><strong>Cloud Data:</strong></p>
            <ul>
              <li>When you sign in, cloud data is retained until you delete your account or delete cloud data from settings</li>
              <li>You can delete your cloud data at any time through the app settings</li>
              <li>When you delete your account, all cloud data is permanently removed</li>
            </ul>

            <p><strong>Authentication Data:</strong></p>
            <ul>
              <li>Authentication tokens are stored securely and automatically refreshed</li>
              <li>You can revoke access at any time through your Google or Apple account settings</li>
            </ul>

            <h3>Transfer of Your Personal Data</h3>

            <p>Your information, including Personal Data, is processed locally on your device. When you sign in and cloud synchronization is active:</p>

            <ul>
              <li>Data is encrypted before transmission</li>
              <li>Data is stored on Firebase servers (Google Cloud Platform)</li>
              <li>All data transfers use secure, encrypted connections</li>
              <li>You can sign out to stop future data transmission and synchronization</li>
            </ul>

            <h3>Delete Your Personal Data</h3>

            <p>You have the right to delete or request assistance in deleting the Personal Data that we have collected about you.</p>

            <p><strong>Local Data Deletion:</strong></p>
            <ul>
              <li>Delete specific scenarios or calculations through the app interface</li>
              <li>Delete all app data by uninstalling the app</li>
              <li>Clear authentication data through device settings</li>
            </ul>

            <p><strong>Cloud Data Deletion:</strong></p>
            <ul>
              <li>Delete your account through the app settings to remove all cloud data</li>
              <li>Sign out to stop future data synchronization</li>
              <li>Contact us at mugglelabs.tech@gmail.com for assistance with data deletion</li>
            </ul>

            <p><strong>Authentication Data:</strong></p>
            <ul>
              <li>Revoke app access through your Google or Apple account settings</li>
              <li>Clear stored authentication tokens through the app settings</li>
            </ul>

            <h3>Disclosure of Your Personal Data</h3>

            <h4>Law Enforcement</h4>

            <p>Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

            <h4>Other Legal Requirements</h4>

            <p>We may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul>
              <li>Comply with a legal obligation</li>
              <li>Protect and defend our rights or property</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ul>

            <h3>Security of Your Personal Data</h3>

            <p>The security of your Personal Data is important to us. We implement appropriate technical and organizational measures to protect your data:</p>

            <ul>
              <li><strong>Local Encryption</strong>: All sensitive data is encrypted on your device</li>
              <li><strong>Secure Storage</strong>: Authentication tokens are stored using platform-specific secure storage</li>
              <li><strong>Encrypted Transmission</strong>: All data transmission uses secure, encrypted connections</li>
              <li><strong>No External Tracking</strong>: We do not use analytics or tracking services</li>
              <li><strong>Privacy by Design</strong>: The app is designed to work offline with optional cloud features</li>
            </ul>

            <p>However, remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

            <h2>Children's Privacy</h2>

            <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from anyone under the age of 13 without verification of parental consent, we take steps to remove that information from our systems.</p>

            <p>If we need to rely on consent as a legal basis for processing your information and your country requires consent from a parent, we may require your parent's consent before we collect and use that information.</p>

            <h2>Third-Party Services</h2>

            <p>Our Service uses the following third-party services:</p>

            <p><strong>Google Sign-In:</strong></p>
            <ul>
              <li>Used for authentication</li>
              <li>Collects: email, name, profile picture</li>
              <li>Privacy Policy: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a></li>
            </ul>

            <p><strong>Apple Sign-In:</strong></p>
            <ul>
              <li>Used for authentication on iOS devices</li>
              <li>Collects: email, name (if provided)</li>
              <li>Privacy Policy: <a href="https://www.apple.com/privacy/" target="_blank" rel="noopener noreferrer">https://www.apple.com/privacy/</a></li>
            </ul>

            <p><strong>Firebase (Google Cloud Platform):</strong></p>
            <ul>
              <li>Used for cloud data synchronization when you sign in</li>
              <li>Data is encrypted and stored securely</li>
              <li>Privacy Policy: <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener noreferrer">https://firebase.google.com/support/privacy</a></li>
            </ul>

            <h2>Changes to this Privacy Policy</h2>

            <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.</p>

            <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective.</p>

            <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

            <h2>Contact Us</h2>

            <p>If you have any questions about this Privacy Policy, you can contact us:</p>

            <ul>
              <li>By email: <a href="mailto:mugglelabs.tech@gmail.com">mugglelabs.tech@gmail.com</a></li>
            </ul>

            <h2>Independent Developer Notice</h2>

            <p>FirePath is developed and maintained by an independent developer, not a company. This privacy policy reflects our commitment to protecting your privacy and being transparent about our data practices. We are not affiliated with any financial institutions or investment companies.</p>

            <hr />

            <p className="text-sm text-muted-foreground italic">
              This Privacy Policy is designed to be transparent about how FirePath handles your data. Your privacy and the security of your financial information are our top priorities.
            </p>
          </article>
        </div>
      </main>
      <Footer />
    </div>
  );
}
